//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ProjectAgent.rc
//
#define IDS_PROJNAME                    100
#define IDS_NWC_MESSAGE                 101
#define IDS_LWC_MESSAGE                 102
#define IDD_CAPACITY_OPTIONS            102
#define IDD_PIER_LAYOUT_PAGE            106
#define IDD_BEARINGS_PAGE               202
#define IDD_SUPERSTRUCTURE_LAYOUT_PAGE  204
#define IDC_NEG_MOMENT_CHECK            204
#define IDD_DESIGN_LIVE_LOAD_REACTIONS  205
#define IDD_LEGAL_LIVE_LOAD_REACTIONS   206
#define IDD_PERMIT_LIVE_LOAD_REACTIONS  207
#define IDD_RATING_OPTIONS              208
#define IDD_PROJECTPROPERTIES           209
#define IDC_LF_PERMIT_ROUTINE           210
#define IDC_LF_PERMIT_ROUTINE_SERVICEI  211
#define IDC_DECK_ELEVATION              212
#define IDC_DECK_ELEVATION_UNIT         213
#define IDC_CPO                         214
#define IDC_CPO_UNIT                    215
#define IDC_BLO                         216
#define IDC_BLO_UNIT                    217
#define IDC_SKEW                        218
#define IDC_BEARING_LINE_COUNT          219
#define IDC_BACK_REF_BEARING_LIST       220
#define IDC_AHEAD_REF_BEARING_LIST      221
#define IDC_BACK_REF_BEARING_LOCATION   222
#define IDC_AHEAD_REF_BEARING_LOCATION  223
#define IDC_BACK_REF_BEARING_LOCATION_UNIT 224
#define IDC_AHEAD_REF_BEARING_LOCATION_UNIT 225
#define IDC_BACK_REF_BEARING_DATUM      226
#define IDC_AHEAD_REF_BEARING_DATUM     227
#define IDC_ADD_BACK                    228
#define IDC_ADD_AHEAD                   229
#define IDC_REMOVE_BACK                 230
#define IDC_REMOVE_AHEAD                231
#define IDC_BACK_LABEL                  232
#define IDC_AHEAD_LABEL                 233
#define IDC_COPY_AHEAD                  234
#define IDC_COPY_BACK                   235
#define IDC_PIER_TYPE                   236
#define IDC_AHEAD_BEARING_LABEL         237
#define IDC_AHEAD_BEARING_LABEL1        238
#define IDC_AHEAD_BEARING_LABEL2        239
#define IDC_AHEAD_BEARING_LABEL3        240
#define IDC_DIMENSIONS                  241
#define IDC_CURB_LINE_MEASUREMENT       242
#define IDC_LCO                         243
#define IDC_LCO_UNIT                    244
#define IDC_RCO                         245
#define IDC_RCO_UNIT                    246
#define IDC_SL                          247
#define IDC_SL_UNIT                     248
#define IDC_SR                          249
#define IDC_LF_LEGAL_SPECIAL            250
#define IDC_SR_UNIT                     251
#define IDC_LF_LEGAL_EMERGENCY          252
#define IDC_DW                          253
#define IDC_DW_STRENGTH_I               254
#define IDC_LF_OPERATING                255
#define IDC_DESIGN_GRID                 256
#define IDC_DW_SERVICE_I                257
#define IDC_LEGAL_ROUTINE_GRID          258
#define IDC_DW_STRENGTH_II              259
#define IDC_LEGAL_SPECIAL_GRID          260
#define IDC_PERMIT_ROUTINE_GRID         261
#define IDC_PERMIT_SPECIAL_GRID         262
#define IDC_DESIGN_ADD                  263
#define IDC_DESIGN_REMOVE               264
#define IDC_LEGAL_SPECIAL_GRID2         265
#define IDC_LEGAL_EMERGENCY_GRID        266
#define IDC_LEGAL_ROUTINE_ADD           267
#define IDC_LEGAL_ROUTINE_REMOVE        268
#define IDC_DC_STRENGTH_I               269
#define IDC_LEGAL_SPECIAL_ADD           270
#define IDC_DC_SERVICE_I                271
#define IDC_LEGAL_SPECIAL_REMOVE        272
#define IDC_DC_STRENGTH_II              273
#define IDC_PERMIT_ROUTINE_ADD          274
#define IDC_PERMIT_ROUTINE_REMOVE       275
#define IDC_PERMIT_SPECIAL_ADD          276
#define IDC_PERMIT_SPECIAL_REMOVE       277
#define IDC_LF_INVENTORY                278
#define IDC_LF_LEGAL_ROUTINE            279
#define IDC_LF_PERMIT_SPECIAL           280
#define IDC_LF_PERMIT_SPECIAL2          281
#define IDC_LF_PERMIT_SPECIAL_SERVICEI  281
#define IDC_LEGAL_EMERGENCY_ADD         282
#define IDC_LEGAL_EMERGENCY_REMOVE      283
#define IDD_CONCRETE_DETAILS            290
#define IDC_PIER_POINT_GRID             290
#define IDC_CONCRETE_TYPE               291
#define IDC_ADD_PIERPOINT               291
#define IDC_FC_LABEL                    292
#define IDC_REMOVE_PIERPOINT            292
#define IDC_FC                          293
#define IDC_FC_UNIT                     294
#define IDC_DS_TITLE                    295
#define IDC_DS                          296
#define IDC_DS_UNIT                     297
#define IDC_COLUMN_GRID                 297
#define IDC_ADD_COLUMN                  298
#define IDC_DW_UNIT                     299
#define IDC_REMOVE_COLUMN               300
#define IDC_MOD_E                       301
#define IDC_BACK_REACTION_TYPE          302
#define IDC_AHEAD_REACTION_TYPE         303
#define IDC_EC                          304
#define IDC_BACK_REACTION_TYPE_LABEL    305
#define IDC_EC_UNIT                     306
#define IDC_AHEAD_REACTION_TYPE_LABEL   307
#define IDC_AGG_SIZE                    308
#define IDC_AGG_SIZE_UNIT               309
#define IDC_CR_STRENGTH_I               310
#define IDC_SH_STRENGTH_I               311
#define IDC_PS_STRENGTH_I               312
#define IDC_SLAB_DEPTH                  313
#define IDC_CR_SERVICE_I                314
#define IDC_SLAB_DEPTH_UNIT             315
#define IDC_SH_SERVICE_I                316
#define IDC_BACK_BRG_OFFSET             317
#define IDC_AHEAD_BRG_OFFSET            318
#define IDC_BACK_BRG_OFFSET_UNIT        319
#define IDC_AHEAD_BRG_OFFSET_UNIT       320
#define IDC_BACK_BRG_OFFSET_LABEL1      321
#define IDC_REACTION_APPLICATION        322
#define IDC_AHEAD_BRG_OFFSET_LABEL1     323
#define IDC_COMBO1                      324
#define IDC_PERMIT_FACTORS              325
#define IDC_BACK_BRG_OFFSET_LABEL2      326
#define IDC_PERMIT_FACTORS2             326
#define IDC_EMERGENCY_FACTORS           326
#define IDC_DESIGN_RATING               327
#define IDC_NEG_MOMENT_WIDTH            327
#define IDC_AHEAD_BRG_OFFSET_LABEL2     328
#define IDC_NEG_MOMENT_WIDTH_UNIT       328
#define IDC_DESIGN_SHEAR                329
#define IDC_STATIC_MOM                  329
#define IDC_LEGAL_RATING                330
#define IDC_H1L_LABEL                   330
#define IDC_PS_SERVICE_I                331
#define IDC_H1L                         331
#define IDC_LEGAL_SHEAR                 332
#define IDC_H1L_UNIT                    332
#define IDC_CR_STRENGTH_II              333
#define IDC_H2L_LABEL                   333
#define IDC_PERMIT_RATING               334
#define IDC_H2L                         334
#define IDC_SH_STRENGTH_II              335
#define IDC_H2L_UNIT                    335
#define IDC_PERMIT_SHEAR                336
#define IDC_X1L_LABEL                   336
#define IDC_PS_STRENGTH_I2              337
#define IDC_X1L                         337
#define IDC_PS_STRENGTH_II              338
#define IDC_X1L_UNIT                    338
#define IDC_PERMIT_YIELD_STRESS         339
#define IDC_X2L_LABEL                   339
#define IDC_OHL_LABEL                   339
#define IDC_ALLOWABLE_STRESS_LABEL      340
#define IDC_X2L                         340
#define IDC_ALLOWABLE_STRESS            341
#define IDC_X2L_UNIT                    341
#define IDC_ALLOWABLE_STRESS_TAG        342
#define IDC_X1R_LABEL                   342
#define IDC_PHI_COMPRESSION             343
#define IDC_X1R                         343
#define IDC_PHI_TENSION                 344
#define IDC_X1R_UNIT                    344
#define IDC_EDIT3                       345
#define X2R_LABEL                       345
#define IDC_OHR_LABEL                   345
#define IDC_PHI_SHEAR                   346
#define IDC_X2R                         346
#define IDC_SYSTEM_FACTOR_FLEXURE       347
#define IDC_X2R_UNIT                    347
#define IDC_X1R_UNIT2                   347
#define IDC_SYSTEM_FACTOR_SHEAR         348
#define IDC_LRFD_LABEL                  349
#define IDC_LRFR_LABEL                  350
#define IDC_LRFD                        351
#define IDC_LRFR                        352
#define IDC_LL_STEP                     353
#define IDC_LL_STEP_UNIT                354
#define IDC_EDIT1                       355
#define IDC_MAX_LANES                   356
#define IDD_AASHTO_CONCRETE             500
#define IDB_EDIT_PIER                   500
#define IDC_EC_K1_LABEL                 501
#define IDB_EDIT_OPTIONS                501
#define IDD_ANALYSIS_OPTIONS            501
#define IDC_EC_K1                       502
#define IDC_EC_K2_LABEL                 503
#define IDC_EC_K2                       504
#define IDC_CREEP_K1_LABEL              505
#define IDC_CREEP_K1                    506
#define IDC_CREEP_K2_LABEL              507
#define IDC_CREEP_K2                    508
#define IDC_SHRINKAGE_K1_LABEL          509
#define IDC_SHRINKAGE_K1                510
#define IDC_SHRINKAGE_K2_LABEL          511
#define IDC_SHRINKAGE_K2                512
#define IDC_HAS_AGG_STRENGTH            513
#define IDC_AGG_STRENGTH                514
#define IDC_AGG_STRENGTH_T              515
#define IDC_PIER_LAYOUT_GUIDE           1113
#define IDD_PIER_LAYOUT_COMMON          1117
#define IDD_PIER_LAYOUT_SCALLOPED       1119
#define IDD_PIER_LAYOUT_USERDEFINED     1120
#define IDC_CONDITION_FACTOR            1260
#define IDC_CONDITION_FACTOR_TYPE       1407
#define IDC_PIER_LAYOUT_TYPE            1408
#define IDC_REFCOLUMN_MEASUREMENT       1423
#define IDC_REFCOLUMN_OFFSET            1424
#define IDC_REFCOLUMN_OFFSET_UNIT       1425
#define IDC_BACK_BEARING_GRID           1475
#define IDC_AHEAD_BEARING_GRID          1476
#define IDC_REFCOLUMN                   1546
#define IDC_X5                          1617
#define IDC_OHL                         1617
#define IDC_HEIGHT_MEASURE              1731
#define IDC_R                           1746
#define IDC_H1                          1747
#define IDC_H2                          1748
#define IDC_H3                          1749
#define IDC_H1R                         1749
#define IDC_H4                          1750
#define IDC_D                           1750
#define IDC_H2R                         1750
#define IDC_X1                          1751
#define IDC_X2                          1752
#define IDC_W                           1753
#define IDC_X6                          1754
#define IDC_OHR                         1754
#define IDC_R_UNIT                      1809
#define IDC_R_LABEL                     1810
#define IDC_PIER_LAYOUT                 1811
#define IDC_H1_UNIT                     1812
#define IDC_H1_LABEL                    1813
#define IDC_H2_LABEL                    1814
#define IDC_H2_UNIT                     1815
#define IDC_H1R_LABEL                   1816
#define IDC_H3_UNIT                     1817
#define IDC_H1R_UNIT                    1817
#define IDC_H4_LABEL                    1818
#define IDC_D_LABEL                     1818
#define IDC_H2R_LABEL                   1818
#define IDC_H4_UNIT                     1819
#define IDC_D_UNIT                      1819
#define IDC_H2R_UNIT                    1819
#define IDC_X1_LABEL                    1820
#define IDC_X1_UNIT                     1821
#define IDC_X2_LABEL                    1822
#define IDC_X2_UNIT                     1823
#define IDC_W_UNIT                      1826
#define OHL_LABEL                       1827
#define IDC_X5_UNIT                     1828
#define IDC_OHL_UNIT                    1828
#define IDC_W_LABEL                     1829
#define IDC_X3                          1830
#define IDC_X3_UNIT                     1831
#define IDC_X4                          1832
#define IDC_X4_UNIT                     1833
#define IDC_H                           1836
#define IDC_H_UNIT                      1837
#define IDC_X5_LABEL                    1847
#define IDC_X6_UNIT                     1848
#define IDC_OHR_UNIT                    1848
#define IDC_X6_LABEL                    1849
#define IDC_BRIDGE                      1850
#define IDC_BRIDGEID                    1851
#define IDC_PIER_LAYOUT_LABEL           1851
#define IDC_JOBNUMBER                   1852
#define IDC_ENGINEER                    1853
#define IDC_COMPANY                     1854
#define IDC_COMMENTS                    1855
#define IDC_SHOW_DIALOG                 1856
#define IDC_FIXITY_LABEL                1856
#define IDC_FIXITY                      1857
#define IDC_CAP_GROUP                   1884
#define IDC_COLUMN_GROUP                1885
#define IDC_STATIC_BOUNDS               2070
#define OHR_LABEL                       12880
#define ID_VIEW_PIER                    33030
#define ID_EDIT_PROJECT_NAME            50000
#define ID_EDIT_PIER                    50001
#define ID_EDIT_OPTIONS                 50002
#define ID_PROPERTIES                   50006
#define ID_FILE_PROJECT_PROPERTIES      50007
#define ID_EDIT_PROPERTIES              50008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         50009
#define _APS_NEXT_CONTROL_VALUE         348
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
